-- Table: public.users

-- DROP TABLE IF EXISTS public.user_profiles;

CREATE TABLE IF NOT EXISTS public.user_profiles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	user_id bigint NOT NULL,
    first_name text COLLATE pg_catalog."default",
	last_name text COLLATE pg_catalog."default",
	email text COLLATE pg_catalog."default",
	CONSTRAINT "PK_user_profiles" PRIMARY KEY (id),
    CONSTRAINT "FK_user_profiles_users" FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION   
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_profiles
    OWNER to otuspostgres;
	
	
	
INSERT INTO public.user_profiles(
user_id, first_name, last_name, email)
VALUES ('1', 'Aegon', 'Targaryen','AegonTargaryien@gmail.com');


{
    "login": "JohnSnowAegon",
    "password": "J123123123123",
    "firstName": "JohnSnow22",
    "lastName": "Targaryien22",
    "email": "Targaryien22@gmail.com"    
}