apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework8orderproductservice
  labels:
    app: homework8orderproductservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework8orderproductservice
  template:
    metadata:
      labels:
        app: homework8orderproductservice
    spec:
      containers:
      - name: homework8orderproductservice
        image: flash1200/homework8_orderproductservice:firstversion
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
          - name: Database__ConnectionString
            valueFrom:
              secretKeyRef:
                name: "homework8orderproductservicesecret"
                key: "homework8orderproductservicedbconnectionstring"