apiVersion: v1
kind: Service
metadata:
  name: homework8notificationservice
  labels:
    app: homework8notificationservice
spec:
  type: LoadBalancer
  ports:
  - name: homework8-http
    port: 91
    protocol: TCP
    targetPort: 8080
  - name: homework8-https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: homework8notificationservice