apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework8warehouseservice
  labels:
    app: homework8warehouseservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework8warehouseservice
  template:
    metadata:
      labels:
        app: homework8warehouseservice
    spec:
      containers:
      - name: homework8warehouseservice
        image: flash1200/homework8_warehouseservice:firstversion
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
          - name: Database__ConnectionString
            valueFrom:
              secretKeyRef:
                name: "homework8warehouseservicesecret"
                key: "homework8warehouseservicedbconnectionstring"